// Esia - the precompiled shader library (generated by tools/shaders/build_shaders.py into
// src/esia/shaders/generated and checked in, so no backend needs a shader compiler to build).
//
// A backend picks its Format once (Caps::shaderFormat) and asks for each program's two stages:
//
//   const shaders::ShaderBlob* vs = shaders::Find(shaders::Format::Glsl330, rhi::ShaderProgram::Fx, shaders::Stage::Vertex);
//
// Text formats (GLSL, ESSL, MSL) are null-terminated source; binary formats (SPIR-V, DXBC, DXIL) are bytecode.
// The Direct3D formats need Microsoft's compilers (fxc / DXC, see tools/shaders/build_shaders.py): until a Windows
// run added them, Available() is false for them and the D3D backends compile FindSource()'s HLSL with D3DCompile.
// GLSL / ESSL have combined samplers: `textures` maps each sampler uniform to its RHI texture slot and sampler
// (0 linear clamp, 1 point clamp); uniform blocks are named WgtFrame / WgtPass / WgtDraw (bind them to 0 / 1 / 2).
// MSL uses the Vulkan binding numbers as Metal indices (esia_common.hlsli); its entry point is `esia_main`.
#pragma once
#include "esia/rhi/rhi.hpp"

namespace esia::shaders
{
    enum class Format : std::uint8_t
    {
        SpirV,     // Vulkan 1.0, FX instances in a storage buffer
        Glsl330,   // OpenGL 3.3 core, FX instances in an RGBA32F texture
        Essl300,   // OpenGL ES 3.0 / WebGL 2, FX instances in an RGBA32F texture
        Msl,       // Metal 2.0 source, FX instances in a device buffer
        DxbcSm5,   // Direct3D 11 / 12 (fxc vs_5_0 / ps_5_0), structured buffer
        DxbcSm4,   // Direct3D 10 (fxc vs_4_0 / ps_4_0), RGBA32F texture
        Dxil,      // Direct3D 12 shader model 6 (DXC), structured buffer
        DxbcSm3,   // Direct3D 9 (fxc vs_3_0 / ps_3_0 with the D3D9 backend's SM3 prelude), RGBA32F texture; no TextLcd
        Count
    };
    ESIA_API const char* FormatName(Format f);
    // How FX instances reach this format's shaders (what the backend must report in Caps::fxStorage).
    ESIA_API rhi::FxStorage FxStorageOf(Format f);

    enum class Stage : std::uint8_t { Vertex = 0, Pixel = 1 };

    struct TextureBinding
    {
        const char* name;   // GLSL uniform name of the combined sampler
        int slot;           // RHI texture slot (rhi::kSlotTexture ...)
        int sampler;        // 0 linear clamp, 1 point clamp
    };

    struct ShaderBlob
    {
        int program;        // rhi::ShaderProgram
        int stage;          // Stage
        const char* entry;  // HLSL entry point it was compiled from
        const unsigned char* data;
        std::size_t size;   // bytes (text formats: without the terminating 0)
        bool text;
        const TextureBinding* textures;
        int textureCount;
    };

    struct SourceFile
    {
        const char* name;   // "esia_common.hlsli", "esia_fx.hlsl" ...
        const char* text;
    };

    // nullptr when the format was not generated for this checkout (DXBC / DXIL need fxc / DXC, see the script).
    ESIA_API const ShaderBlob* Find(Format format, rhi::ShaderProgram program, Stage stage);
    ESIA_API bool Available(Format format);
    // HLSL sources for runtime compilation of user effects (include handler of D3DCompile / DXC).
    ESIA_API const char* FindSource(const char* name);
}
