# LLVM toolchain for macOS: clang / clang++ with lld (ld64.lld).
# Uses the LLVM from Homebrew (brew install llvm lld) when present; Apple's SDK comes from xcrun.
# Metal shaders are compiled by the Metal backend with xcrun metal (see docs/backends/README.md).
if(EXISTS /opt/homebrew/opt/llvm/bin/clang++)
    set(_esia_llvm /opt/homebrew/opt/llvm/bin)
elseif(EXISTS /usr/local/opt/llvm/bin/clang++)
    set(_esia_llvm /usr/local/opt/llvm/bin)
endif()
if(_esia_llvm)
    set(CMAKE_C_COMPILER   ${_esia_llvm}/clang)
    set(CMAKE_CXX_COMPILER ${_esia_llvm}/clang++)
else()
    set(CMAKE_C_COMPILER   clang)
    set(CMAKE_CXX_COMPILER clang++)
endif()
if(NOT CMAKE_OSX_SYSROOT)
    execute_process(COMMAND xcrun --show-sdk-path OUTPUT_VARIABLE _esia_sdk OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_esia_sdk)
        set(CMAKE_OSX_SYSROOT ${_esia_sdk} CACHE PATH "")
    endif()
endif()
set(CMAKE_EXE_LINKER_FLAGS_INIT    "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
