# Script mode: embeds files as C++ byte arrays with external linkage.
#   cmake -DOUT=<file.cpp> -DNAMESPACE=<ns> -DPAIRS=sym=file|sym=file... -P EsiaEmbed.cmake
# Every array gets a terminating 0 byte (text blobs are C strings); sizes are known to the caller.
string(REPLACE "|" ";" _pairs "${PAIRS}")
set(_content "// Generated by cmake/EsiaEmbed.cmake - do not edit.\nnamespace ${NAMESPACE}\n{\n")
foreach(_pair ${_pairs})
    string(FIND "${_pair}" "=" _eq)
    string(SUBSTRING "${_pair}" 0 ${_eq} _sym)
    math(EXPR _start "${_eq} + 1")
    string(SUBSTRING "${_pair}" ${_start} -1 _file)
    file(READ "${_file}" _hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" _arr "${_arr}")
    string(APPEND _content "    extern const unsigned char ${_sym}[] = {\n${_arr}0x00};\n")
endforeach()
string(APPEND _content "}\n")
file(WRITE "${OUT}.tmp" "${_content}")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
